#ifndef YACHTROCK_VERSION_INTERNAL
#define YACHTROCK_VERSION_INTERNAL

#define YR_MAJOR 1
#define YR_MINOR 2
#define YR_PATCH 0

#define YR_VERSION_LITERAL YR_XSTR(YR_MAJOR) "." YR_XSTR(YR_MINOR) "." YR_XSTR(YR_PATCH)

#endif
